// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brluhegnifritmtazdfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybHVoZWduaWZyaXRtdGF6ZGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTEwMTgsImV4cCI6MjA2NzE4NzAxOH0.fdLgGATgpcaY_2u9RBBR7SBRr9dMGReQT6GNVtn5z6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});